### ISSUE TITLE
Does not escape @ symbol in task_schedule.cfg

### ISSUE THREAD

**Issue by jeanconn** [sot/task_schedule#14]
Does not escape @ symbol in task_schedule.cfg

IIRC, this is a problem in the actual task descriptions.

See 
https://github.com/sot/acdc/pull/22

**Comment by taldcroft** [comment]
I decided to punt on this after spending a few minutes looking for options that would work. 

The root problem is the Safe `reval`, which insists on seeing the `@` as an array.  Escaping that with `\` didn't work.  Maybe some hack like replacing `@` with `____at____` before calling `reval` and then re-replacing afterward would do the trick?

**Comment by jeanconn** [comment]
If they define safely/correcty outside the task (as notify or alert or whatever), can those values be used safely as variables in the <task>?

**Comment by taldcroft** [comment]
That's a good point.  OTOH the reality is that I think we don't *need* full email addresses in the task, at least so far.  I was thinking a quick mitigation is just checking for `@` and failing with a warning that it doesn't work.  At least for existing tasks it is not a limitation, sending to a bare address (that goes to @head or localhost) is actually fine.
